version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          cache-version: '1.1'
          steps:
            - run: yarn install --frozen-lockfile
            - run:
                name: 'Lint'
                command: yarn run lint
            - run:
                name: 'Test'
                command: yarn run test
            - run:
                name: 'Build'
                command: yarn run build
            - run:
                name: 'Bundle size'
                command: yarn run bundlesize
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: 'Send deploy request to netlify'
          command: curl -X POST -d {} ${NETLIFY_BUILD_URL}

workflows:
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
