name: Build and Test

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile
      - name: 'Lint'
        run: yarn run lint
      - name: 'Test'
        run: yarn run test
      - name: 'Build'
        run: yarn run build
      - name: 'Bundle size'
        run: yarn run bundlesize
