name: CI CD

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile
      - name: 'Lint'
        run: yarn run lint
      - name: 'Test'
        run: yarn run test
      - name: 'Build'
        run: yarn run build
      - name: 'Bundle size'
        run: yarn run bundlesize
  deploy:
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
          NETLIFY_DEPLOY_TO_PROD: true
